# POST http://localhost:3000/clubs/1/books/2/reviews HTTP/1.1
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiZWR1YXJkb0B0ZXN0LmNvbSIsImV4cCI6MTc4MDMxOTk3N30.lpiZELMSF8k0d_i6jpw1JmKWFqvqPZj5tS6jWgZkAEs

# {
#     "rating": 2
# }

# PATCH http://localhost:3000/clubs/1/books/2/reviews HTTP/1.1
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiZWR1YXJkb0B0ZXN0LmNvbSIsImV4cCI6MTc4MDMxOTk3N30.lpiZELMSF8k0d_i6jpw1JmKWFqvqPZj5tS6jWgZkAEs

# {
#     "rating": 4,
#     "content": "Best book ever!"
# }


DELETE  http://localhost:3000/clubs/1/books/2/reviews/1 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiZWR1YXJkb0B0ZXN0LmNvbSIsImV4cCI6MTc4MDMxOTk3N30.lpiZELMSF8k0d_i6jpw1JmKWFqvqPZj5tS6jWgZkAEs

# GET  http://localhost:3000/clubs/1/books/2/reviews HTTP/1.1
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiZWR1YXJkb0B0ZXN0LmNvbSIsImV4cCI6MTc4MDMxOTk3N30.lpiZELMSF8k0d_i6jpw1JmKWFqvqPZj5tS6jWgZkAEs
